version: "3.9"

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  producer:
    build:
      context: ./producer
    container_name: kafka-producer
    image: kafka-producer/producer:latest
    environment:
      - SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE:-dev}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8082:8082"
    depends_on:
      - kafka

  consumer:
    build:
      context: ./consumer
    container_name: kafka-consumer
    image: kafka-consumer/consumer:latest
    environment:
      - SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE:-dev}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8080:8080"
    depends_on:
      - kafka
