version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
  consumer:
    build: consumer
    image: kafka-consumer/consumer:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}"
    ports:
      - "8080:8080"
    depends_on:
      - kafka
  producer:
    build: producer
    image: kafka-producer/producer:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}"
    ports:
      - "8082:8082"
    depends_on:
      - kafka